#   SPDX-License-Identifier: BSD-3-Clause
#   Copyright (C) 2023 Intel Corporation.
#   All rights reserved.
#
SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

LIBNAME = vbdev_dualtier
SRCS = vbdev_dualtier.c
SRCS += vbdev_dualtier_rpc.c

include $(SPDK_ROOT_DIR)/mk/spdk.lib.mk
